# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMDR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('loan', models.IntegerField(blank=True, null=True)),
                ('insuranceknown', models.BooleanField()),
                ('insurance', models.IntegerField(blank=True, null=True)),
                ('gamemode', models.CharField(blank=True, max_length=32, null=True)),
                ('group', models.CharField(blank=True, max_length=32, null=True)),
                ('rank_known', models.BooleanField()),
                ('rank_progress_known', models.BooleanField()),
                ('rank_combat', models.IntegerField(blank=True, null=True)),
                ('rank_combat_progress', models.IntegerField(blank=True, null=True)),
                ('rank_trade', models.IntegerField(blank=True, null=True)),
                ('rank_trade_progress', models.IntegerField(blank=True, null=True)),
                ('rank_explore', models.IntegerField(blank=True, null=True)),
                ('rank_explore_progress', models.IntegerField(blank=True, null=True)),
                ('rank_cqc', models.IntegerField(blank=True, null=True)),
                ('rank_cqc_progress', models.IntegerField(blank=True, null=True)),
                ('rank_federation', models.IntegerField(blank=True, null=True)),
                ('rank_federation_progress', models.IntegerField(blank=True, null=True)),
                ('rank_empire', models.IntegerField(blank=True, null=True)),
                ('rank_empire_progress', models.IntegerField(blank=True, null=True)),
                ('rep_federation', models.IntegerField(blank=True, null=True)),
                ('rep_empire', models.IntegerField(blank=True, null=True)),
                ('rep_alliance', models.IntegerField(blank=True, null=True)),
                ('rep_thargoid', models.IntegerField(blank=True, null=True)),
                ('currentshipid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardpointMount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotsize', models.IntegerField()),
                ('populated', models.BooleanField()),
                ('attached', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotsize', models.IntegerField()),
                ('populated', models.BooleanField()),
                ('attached', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=64, unique=True)),
                ('shipid', models.IntegerField()),
                ('shiptype', models.CharField(max_length=32)),
                ('shipname', models.CharField(blank=True, max_length=64, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True)),
                ('cclass', models.IntegerField(blank=True, null=True)),
                ('hullcost', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('boost', models.IntegerField(blank=True, null=True)),
                ('boostenergy', models.IntegerField(blank=True, null=True)),
                ('agility', models.IntegerField(blank=True, null=True)),
                ('baseshieldstrength', models.IntegerField(blank=True, null=True)),
                ('basearmour', models.IntegerField(blank=True, null=True)),
                ('masslock', models.IntegerField(blank=True, null=True)),
                ('pipspeed', models.FloatField(blank=True, null=True)),
                ('retailcost', models.IntegerField(blank=True, null=True)),
                ('powerplant', models.CharField(max_length=64)),
                ('thrusters', models.CharField(max_length=64)),
                ('fsd', models.CharField(max_length=64)),
                ('lifesupport', models.CharField(max_length=64)),
                ('powerdist', models.CharField(max_length=64)),
                ('sensors', models.CharField(max_length=64)),
                ('fueltank', models.CharField(max_length=64)),
                ('hullmass', models.IntegerField(blank=True, null=True)),
                ('fuelcapacity', models.IntegerField(blank=True, null=True)),
                ('cargocapacity', models.IntegerField(blank=True, null=True)),
                ('ladenmass', models.IntegerField(blank=True, null=True)),
                ('unladenmass', models.IntegerField(blank=True, null=True)),
                ('unladenrange', models.IntegerField(blank=True, null=True)),
                ('fulltankrange', models.IntegerField(blank=True, null=True)),
                ('ladenrange', models.IntegerField(blank=True, null=True)),
                ('cmdr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edacapi.CMDR')),
            ],
        ),
        migrations.AddField(
            model_name='moduleslot',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edacapi.Ship'),
        ),
        migrations.AddField(
            model_name='hardpointmount',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edacapi.Ship'),
        ),
    ]
