# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edacapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edsmid', models.IntegerField(null=True, unique=True)),
                ('edsmdate', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='credits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='gamemode',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='group',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='insurance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='loan',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rank_combat',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rank_combat_progress',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rank_cqc',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rank_cqc_progress',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rank_empire',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rank_empire_progress',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rank_explore',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rank_explore_progress',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rank_federation',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rank_federation_progress',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rank_trade',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rank_trade_progress',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rep_alliance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rep_empire',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rep_federation',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cmdr',
            name='rep_thargoid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hardpointmount',
            name='attached',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='moduleslot',
            name='attached',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='ship',
            name='agility',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='basearmour',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='baseshieldstrength',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='boost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='boostenergy',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='cargocapacity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='cclass',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='fuelcapacity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='fulltankrange',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='hullcost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='hullmass',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='ladenmass',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='ladenrange',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='ship',
            name='masslock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='pipspeed',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='retailcost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='shipname',
            field=models.CharField(blank=True, default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='ship',
            name='speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='unladenmass',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='unladenrange',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
