# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edacapi', '0002_auto_20160910_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='coord_x',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='system',
            name='coord_y',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='system',
            name='coord_z',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
